// Central icon surface. The handoff uses Lucide (line, 24px grid, ~2px stroke,
// currentColor) — we use lucide-react directly in production.
import {
  Scale,
  Briefcase,
  Building2,
  Gavel,
  Cpu,
  TrendingDown,
  FileText,
  Shield,
  Calendar,
  Globe,
  ArrowRight,
  ArrowLeft,
  Check,
  CheckCircle,
  ShoppingBag,
  Download,
  ChevronDown,
  Clock,
  Mail,
  Phone,
  MapPin,
  X,
  Menu,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/content";

export {
  Scale,
  Briefcase,
  Building2,
  Gavel,
  Cpu,
  TrendingDown,
  FileText,
  Shield,
  Calendar,
  Globe,
  ArrowRight,
  ArrowLeft,
  Check,
  CheckCircle,
  ShoppingBag,
  Download,
  ChevronDown,
  Clock,
  Mail,
  Phone,
  MapPin,
  X,
  Menu,
};

// Resolve a string icon key (stored in content data) to its component.
export const iconByName: Record<IconName, LucideIcon> = {
  TrendingDown,
  Briefcase,
  Building2,
  Scale,
  Gavel,
  Cpu,
  FileText,
  Shield,
};
